name: Maven CI/CD
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-java?tab=readme-ov-file#caching-packages-dependencies
      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: 📦 Install dependencies
        run: mvn install
      - name: 🧪 Run tests with coverage
        run: mvn test jacoco:report