name: Translate Properties Files

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      tgt_lang:
        description: 'Target language (must be supported by argostranslate)'
        required: true
        type: choice
        options:
          - ar
          - az
          - bg
          - bn
          - ca
          - cs
          - da
          - de
          - el
          - en
          - eo
          - es
          - et
          - eu
          - fa
          - fi
          - fr
          - ga
          - gl
          - he
          - hi
          - hu
          - id
          - it
          - ja
          - ko
          - ky
          - lt
          - lv
          - ms
          - nb
          - nl
          - pt-BR
          - pl
          - pt
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sv
          - th
          - tl
          - tr
          - uk
          - ur
          - vi
          - zh-Hans
          - zh-Hant

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: ☕ Install dependencies
        run: | 
          pip install -r requirements.txt
      - name: 🤖 Translate _en.properties files
        run: |
          python scripts/translate_java_test_strings.py --tgt-lang "${{ github.event.inputs.tgt_lang }}"
          python scripts/translate_properties.py --tgt-lang "${{ github.event.inputs.tgt_lang }}"
        env:
          SRC_DIR: common/src/main/resources
      - name: 💅 Commit and push translated files
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          title: "Add ${{ github.event.inputs.tgt_lang }} support"
          commit-message: "feat: Add ${{github.event.inputs.tgt_lang}} support"
          branch: "automated/translator-${{github.event.inputs.tgt_lang}}-${{ github.run_id }}"
          base: main
